# Generated by Django 6.1.1 on 2026-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('primary', 'Primary Education'), ('junior_high', 'Junior High School'), ('senior_high', 'Senior High School'), ('tertiary', 'Tertiary Education')], max_length=20)),
                ('program', models.CharField(blank=True, help_text='e.g. "Bachelor of Science in Information Technology (BSIT)"', max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('maps_url', models.URLField(blank=True)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_year'],
            },
        ),
    ]
