# Generated by Django 6.1.1 on 2026-09-22 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.PositiveSmallIntegerField(help_text='Visual self-assessment, not a measured score.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='skills.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
