# Generated by Django 6.1.1 on 2026-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(help_text='The highlighted part of the hero name, e.g. "Iana Berches".', max_length=150)),
                ('title', models.CharField(help_text='e.g. "IT Student"', max_length=150)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(help_text='Short intro shown in the hero section.')),
                ('about', models.TextField(blank=True, help_text='Longer bio shown in the About section.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='profile/resume/')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active profile is shown publicly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
